# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'junit stage'
    jobs:
       - job: 'JunitTest'
         displayName: 'Running unit test'
         steps:
            -  script: 'Running sprng demo app unit test'
            - task: Maven@4
              inputs:
                mavenPomFile: 'pom.xml'
                goals: 'test'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                codeCoverageToolOption: 'JaCoCo'
                javaHomeOption: 'JDKVersion'
                mavenVersionOption: 'Default'
                mavenAuthenticateFeed: false
                effectivePomSkip: false
                sonarQubeRunAnalysis: false
                checkStyleRunAnalysis: true
                pmdRunAnalysis: true
